### ISSUE TITLE
Free Space

### ISSUE THREAD

**Issue by johnplantada** [t3kk/BuzzwordBingo#3]
There is no free space.  This is unacceptable.

Expected result:

| B | I | N | G | O |
| --- | --- | --- | --- | --- |
| Synergy | Enhancement | Agile | Fragile | Cats |
| Synergy | Enhancement | Agile | Fragile | Cats |
| Synergy | Enhancement | Free Space | Fragile | Cats |
| Synergy | Enhancement | Agile | Fragile | Cats |
| Synergy | Enhancement | Agile | Fragile | Cats |

Actual result:

| B | I | N | G | O |
| --- | --- | --- | --- | --- |
| Synergy | Enhancement | Agile | Fragile | Cats |
| Synergy | Enhancement | Agile | Fragile | Cats |
| Synergy | Enhancement | Agile | Fragile | Cats |
| Synergy | Enhancement | Agile | Fragile | Cats |
| Synergy | Enhancement | Agile | Fragile | Cats |

Please note that there is no "Free Space" in the actual result.

From Wikipedia:

http://en.wikipedia.org/wiki/Bingo_(U.S.)#Bingo_cards

The five columns of the card are labeled 'B', 'I', 'N', 'G', and 'O' from left to right. The center space is usually marked "Free" or "Free Space", and is considered automatically filled.

**Comment by rdarley** [comment]
I don't have any requirement for a free space. I think this needs to be categorized as a Gap Story and pointed for a future iteration

**Comment by laurelbean** [comment]
We could compromise and add "Free Space" to our dictionary list

**Comment by rdarley** [comment]
We'll have to take that back to the APO and see if they accept it

**Comment by rdarley** [comment]
Free Space has been added
